---
- name: get vm guest status
  shell: 'dmesg | egrep "(on KVM|Virtual HD|VMware|Xen virtual console)"'
  failed_when: False
  check_mode: False
  changed_when: False
  register: vm_status

- name: register is_vm
  set_fact:
    is_vm: True
  when: vm_status.rc == 0

- name: installe debconf-utils
  apt:
    name: debconf-utils
    state: installed
  tags: baseconf, pkg

# timezone
- block:
  - name: get timezone
    command: cat /etc/timezone
    register: zoneinfo
    changed_when: False
    ignore_errors: True
  - name: set timezone
    command: 'echo {{ host_timezone }} > /etc/timezone'
    when: zoneinfo.stdout != host_timezone
  tags: timezone
  when: do_sysadm

# locales
- name: set locales
  lineinfile:
    dest: /etc/locale.gen
    line: '{{ locale }}'
    regexp: '{{ locale }}'
  with_items:
    - en_US.UTF-8 UTF-8
    - fr_FR.UTF-8 UTF-8
  loop_control:
    loop_var: locale
  notify: debian regen locales
  tags: locales
  when: do_sysadm

