---
# packages
- name: packages
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - '{{ root_shell | basename }}'
    - git
    - ntp
    - ldap-utils
    - '{{ pkgs }}'
    - '{{ role_pkgs }}'
    - '{{ host_pkgs }}'
  tags: pkgs


