---
- name: pkgs OpenBSD
  openbsd_pkg:
    name: '{{ openbsd_base_pkgs + host_pkgs + role_pkgs + pkgs }}'
    state: present
  environment:
    PKG_PATH: "http://{{ openbsd_pkg_mirror }}/pub/OpenBSD/{{ ansible_distribution_version }}/packages/{{ ansible_architecture }}/"
  tags: baseconf, pkg
