---
# snmp
- name: config snmpd
  lineinfile:
    line: '{{ item.line }}'
    regexp: '{{ item.regexp }}'
    dest: /etc/snmpd.config
  with_items:
    - { line: 'begemotSnmpdModulePath."ucd" = "/usr/local/lib/snmp_ucd.so"', regexp: '^begemotSnmpdModulePath.*snmp_ucd' }
# bug cpu snmp hostres
#    - { line: 'begemotSnmpdModulePath."hostres" = "/usr/lib/snmp_hostres.so"', regexp: '^begemotSnmpdModulePath.*snmp_hostres' }
  notify: restart bsnmpd

- name: enable bsnmpd
  service:
    name: bsnmpd
    state: started
    enabled: yes
