---
# snmpd
- name: snmpd config file
  lineinfile:
    line: '{{ item.line }}'
    regexp: '{{ item.regexp }}'
    dest: /etc/snmp/snmpd.conf
  with_items:
    - { line: 'agentaddress  udp::161,udp6::161', regexp: '^agentaddress' }
    - { line: 'sysLocation Epicerie', regexp: '^sysLocation' }
    - { line: 'sysContact CRI <c@ec-m.fr>', regexp: '^sysContact' }
  notify: restart snmpd
- name: snmpd config file - access perms
  lineinfile:
    line: 'rocommunity public {{ item }}'
    dest: /etc/snmp/snmpd.conf
    insertbefore: 'rocommunity .* -V systemonly'
    regexp: '^ *rocommunity *public *{{ item }}'
  loop: '{{ [ "127.0.0.1" ] + monitoring_from + admin_from | default([]) | unique }}'
  when: item is not search(":")
  notify: restart snmpd

- name: snmpd config file - access IPv6 perms
  lineinfile:
    line: 'rocommunity6 public {{ item }}'
    dest: /etc/snmp/snmpd.conf
    insertbefore: 'rocommunity .* -V systemonly'
    regexp: '^ *rocommunity6 *public *{{ item }}'
  loop: '{{ [ "::1" ] + monitoring_from + admin_from | default([]) | unique }}'
  when: item is search(":")
  notify: restart snmpd

- name: snmpd config file - hardware monitoring
  lineinfile:
    line: '{{ item }}'
    dest: /etc/snmp/snmpd.conf
  loop:
    - proc  mountd
    - proc  ntalkd    4
    - disk       /     10000
    - disk       /var  5%
    - includeAllDisks  10%
    - load   12 10 5
  notify: restart snmpd
- name: enable snmpd
  service:
    name: snmpd
    state: started
    enabled: yes
