---
# snmpd
- name: snmpd config file
  lineinfile:
    line: '{{ item.line }}'
    regexp: '^{{ item.regexp }}'
    dest: /etc/snmp/snmpd.conf
  with_items:
    - { line: 'agentaddress udp::161,udp6:[::]:161', regexp: 'agent[Aa]ddress' }
    - { line: 'sysLocation Epicerie', regexp: 'sysLocation' }
    - { line: 'sysContact CRI <c@ec-m.fr>', regexp: 'sysContact' }
  notify: restart snmpd

- name: "delete rocommunity[6] -V systemonly"
  lineinfile:
    regexp: '^rocommunity.* -V systemonly'
    state: absent
    dest: /etc/snmp/snmpd.conf
  notify: restart snmpd

- name: cleanup snmpd.conf
  lineinfile:
    regexp: '^ *rocommunity'
    state: absent
  when: snmpd_access_config is not match("/etc/snmp/snmpd.conf")
  notify: restart snmpd

- name: snmpd config file - access perms
  lineinfile:
    line: 'rocommunity public {{ item }}'
    dest: '{{ snmpd_access_config }}'
    insertbefore: 'rocommunity .* -V systemonly'
    regexp: '^ *rocommunity *public *{{ item }}'
    create: yes
  loop: '{{ [ "127.0.0.1" ] + monitoring_from + admin_from | default([]) | unique }}'
  when: item is not search(":")
  notify: restart snmpd

- name: snmpd config file - access IPv6 perms
  lineinfile:
    line: 'rocommunity6 public {{ item }}'
    dest: '{{ snmpd_access_config }}'
    insertbefore: 'rocommunity .* -V systemonly'
    regexp: '^ *rocommunity6 *public *{{ item }}'
    create: yes
  loop: '{{ [ "::1" ] + monitoring_from + admin_from | default([]) | unique }}'
  when: item is search(":")
  notify: restart snmpd

- name: cleanup snmpd.conf
  lineinfile:
    regexp: '^ *{{ item }} *.*$'
    state: absent
  when: snmpd_local_config is not match("/etc/snmp/snmpd.conf")
  notify: restart snmpd
  loop:
    - proc
    - disk
    - includeAllDisks
    - load
  notify: restart snmpd

- name: snmpd config file - hardware monitoring
  lineinfile:
    line: '{{ item }}'
    dest: '{{ snmpd_local_config }}'
    create: yes
  loop:
    - proc  mountd
    - proc  ntalkd    4
    - disk       /     10000
    - disk       /var  5%
    - includeAllDisks  10%
    - load   12 10 5
  notify: restart snmpd

- name: includeDir
  lineinfile:
    dest: /etc/snmp/snmpd.conf
    line: 'includeDir /etc/snmp/snmpd.conf.d'
    regexp: '^ *includeDir'
  notify: restart snmpd
  when: ansible_distribution_major_version | int > 11

- name: enable snmpd
  service:
    name: snmpd
    state: started
    enabled: yes
