---
- name: syslog central
  lineinfile:
    dest: /etc/syslog.conf
    insertbefore: '^!'
    regexp: '^[^#]+notice.*@.*'
    line: '*.notice;cron,ftp,kern,lpr,mail,user.none	@{{ syslog_server }}'
  notify: restart BSD syslogd
  when: syslog_server | default(False)

- name: syslog central / auth
  lineinfile:
    dest: /etc/syslog.conf
    insertbefore: '^!'
    regexp: '^auth.*@.*'
    line: 'auth.info;authpriv.info					@{{ syslog_auth_server | default(syslog_server) }}'
  notify: restart BSD syslogd
  when: syslog_server | default(False)
