---
- name: syslog directory
  file:
    path: /etc/rsyslog.d
    state: directory
    owner: root
    group: root
    mode: '0600'
- name: syslog central
  template:
    src: rsyslog_ecm.conf.j2
    dest: /etc/rsyslog.d/ecm.conf
    mode: '0600'
  notify: restart Debian rsyslog
