---
- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: reconfigure postfix
  command: 'dpkg-reconfigure --frontend noninteractive postfix'
  when: ansible_distribution == 'Debian'

- name: restart smtpd
  service:
    name: smtpd
    state: restarted

- name: newaliases
  command: /usr/bin/newaliases

- name: restart bsnmpd
  service:
    name: bsnmpd
    state: restarted

- name: restart BSD syslogd
  service:
    name: syslogd
    state: restarted

- name: restart Debian rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart ntpd
  service:
    name: '{{ ntp_service }}'
    state: restarted

- name: restart munin
  service:
    name: '{{ munin_service }}'
    state: restarted
